ga4_analytics_data:
    clients:
        default:
            property_id: '%env(ANALYTICS_PROPERTY_ID)%'
            service_account_credentials_json: '%env(ANALYTICS_CREDENTIALS_PATH)%'
            cache:
                enabled: true
                lifetime_in_minutes: 1440
                prefix: 'ga4_analytics_data'
            proxy: ~
            no_proxy: []
    default_client: 'default'
    profiler: true