services:
    _defaults:
        autowire: true
        autoconfigure: true

    Freema\GA4AnalyticsDataBundle\Dev\Controller\:
        resource: '../Controller/'
        tags: ['controller.service_arguments']